version: "3.5"
services:
  nod1a:
    container_name: nod1a
    image: nats
    ports:
      - "8223:8222"
    volumes:
      - /home/nats/clust:/etc/nats
    command: "-c /etc/nats/nod1a.conf"
    networks: ["nats"]
  nod1b:
    container_name: nod1b
    image: nats
    volumes:
      - /home/nats/clust:/etc/nats
    command: "-c /etc/nats/nod1b.conf"
    networks: ["nats"]
    depends_on: ["nod1a"]
  nod2a:
    container_name: nod2a
    image: nats
    volumes:
      - /home/nats/clust:/etc/nats
    command: "-c /etc/nats/nod2a.conf"
    ports:
      - "8222:8222"
    networks: ["nats"]
    depends_on: ["nod1b"]
  nod2b:
    container_name: nod2b
    image: nats
    volumes:
      - /home/nats/clust:/etc/nats
    command: "-c /etc/nats/nod2b.conf"
    networks: ["nats"]
    depends_on: ["nod2a"]
  nod2c:
    container_name: nod2c
    image: nats
    volumes:
      - /home/nats/clust:/etc/nats
    command: "-c /etc/nats/nod2c.conf"
    networks: ["nats"]
    depends_on: ["nod2a"]

networks:
  nats:
    name: nats

