---
# tasks file for nats_autoconfiguration_supercluster_config
- name: Create configuration
  template:
    src: "nats_cfg.j2"
    dest: "/home/ansible/{{ item }}.conf"
    owner: root
    group: root
    mode: 0644
  loop: 
#         Specify the names of the servers to generate the configuration for.
    - nod1a
    - nod1b
    - nod2a
    - nod2b
    - nod2c

